name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: "Test"
        shell: bash
        run: make test

      - name: "Build"
        shell: bash
        run: make build
